### PR TITLE
GROWTH-4812 Remove Noindex: */room/*

### PR DESCRIPTION
**Pull request by augustocorvalan**
Related to https://github.com/1stdibs/dibs-graphql/pull/6907

### IMPORTANT

Commits to robots.txt landing in master will be pushed to production automatically. Only merge pull requests that you're confident should be pushed to production.

### CODE REVIEW

**Comment by twhid** [comment]
the metatag changes launched, correct @augustocorvalan ?

**Comment by augustocorvalan** [comment]
@twhid that's right, linked that PR in the descriptionn

**Comment by augustocorvalan** [comment]
merging this 🚀

**Comment by augustocorvalan** [comment]
Hmm, not seeing this change on prod yet....
Screen Shot 2019-08-08 at 12 23 29 PM

@peterborghard ?

**Comment by peterborghard** [comment]
I just updated the Api token in github, job is running now:

http://janky2.1stdibs.com/job/robots.txt-prod/35/

**Comment by augustocorvalan** [comment]
@peterborghard ty

**Pull request merged**
