### PR TITLE
removed params st, customizable, item-type

### PR DESCRIPTION
**Pull request by nameofname**
### IMPORTANT

Commits to robots.txt landing in master will be pushed to production automatically. Only merge pull requests that you're confident should be pushed to production.

### CODE REVIEW

**Comment by nameofname** [comment]
@twhid @gedas-monginas do you know what the `st` query param is ? SEO wants to remove it because it conflicts with `latest`

**Comment by twhid** [comment]
+ @hellatan

**Comment by nameofname** [comment]
@lilianammmatos @gedas-monginas @twhid @hellatan looks like `st` is for broad search, here's an example of an external link with the param : https://www.1stdibs.com/search/?q=antique%20oil%20jar&st=broad

**Comment by hellatan** [comment]
nice sleuthing @nameofname. here's a test to confirm that - `should assign st with value broad (broad search) param to url`: https://github.com/1stdibs/ferrum/blob/4148f6598770f7451608742f052c0cf76f1c82e5/packages/dibs-buyer-layout/src/components/SearchBar/__test__/SearchBar.spec.jsx#L599

**Comment by nameofname** [comment]
Hmmm. I see that the broad search `st` param will only be applied to /search/ URLs - since those are already disallowed by a separate rule in robots I'm going to say it's ok to kill it for now. I had a conversation with my SEO guy about it and he did some analysis - we don't have many external links to pages with that param, and we definitely don't link to it internally. Low risk, merging now.

**Comment by gedas-monginas** [comment]
if  remember correctly `st` stand for search type ;)

**Pull request merged**
